#!/usr/bin/csh
set case_dir = "../cases/capacity_alpha"
set join_dir = "../cases"
foreach cases (0.04 0.05 0.06 0.07)
	foreach capacity (3 4 5 6 7 8)
		cp -f $case_dir/result_{$cases}_$capacity.txt ./{$cases}$capacity.txt
		if (-e agg_{$cases}.txt) then
			rm -f agg.txt
		endif
		./agg.py $capacity $cases
		rm -f {$cases}$capacity.txt
	end
	mv -f agg.txt $case_dir/agg_{$cases}.txt
end
