#!/usr/bin/csh
# NEED TO PROVIDE AN ARGUMENT AS CAPACITY OF QUANTUM EDGES
set case_dir = "../cases/candidate_capacity"
set join_dir = "../cases"
set cap = $argv
foreach cases (ilp rra hba heu)
	foreach candidate (3 4 5 6 7 8)
		cp -f $case_dir/result_{$cases}_{$cap}_$candidate.txt ./{$cases}$candidate.txt
		if (-e agg_{$cases}.txt) then
			rm -f agg.txt
		endif
		./agg.py $candidate {$cases}
		rm -f {$cases}$candidate.txt
	end
	mv -f agg.txt $case_dir/agg_{$cases}_$cap.txt
end
