#!/usr/bin/csh
set case_dir = "../cases/num_edges"
set join_dir = "../cases"
foreach cases (ilp rra heu)
	if (-e agg.txt) then
		rm -f agg.txt
	endif
	foreach prob (3 4 5 6 7 8)
		cp -f $case_dir/result_${cases}_$prob.txt ./${cases}$prob.txt
		./agg.py $prob $cases
		rm -f ${cases}$prob.txt
	end
	mv -f agg.txt $case_dir/agg_{$cases}.txt
end
