#!/usr/bin/csh
set case_dir = "../cases/candidate_requests"
set join_dir = "../cases"
foreach cases (3 4 5 6)
	foreach num_demands (50 55 60 65 70)
		cp -f $case_dir/result_{$cases}_$num_demands.txt ./{$cases}$num_demands.txt
		if (-e agg_{$cases}.txt) then
			rm -f agg.txt
		endif
		./agg.py $num_demands $cases
		rm -f {$cases}$num_demands.txt
	end
	mv -f agg.txt $case_dir/agg_{$cases}.txt
end
