#!/usr/bin/csh
set case_dir = "../cases/candidate"
set join_dir = "../cases"
foreach cases (ilp rra heu)
#foreach cases (rra)
	foreach candidate (3 4 5 6 7 8)
		cp -f $case_dir/result_{$cases}_$candidate.txt ./{$cases}$candidate.txt
		if (-e agg_{$cases}.txt) then
			rm -f agg.txt
		endif
		./agg.py $candidate $cases
		rm -f {$cases}$candidate.txt
	end
	mv -f agg.txt $case_dir/agg_{$cases}.txt
end
