#!/usr/bin/csh
set case_dir = "../cases/num_nodes"
set join_dir = "../cases"
foreach num_nodes (60 80 100 120 140 160)
#foreach num_nodes ( 60 )
	cp -f $case_dir/Sample_$num_nodes.txt ./Sample.txt
	foreach cases (ilp rra heu)
	#foreach cases (heu)
		cp -f $case_dir/time_num_nodes_$cases.py $join_dir/test.py
		if (-e $join_dir/result.txt) then
			rm -f $join_dir/result.txt
		endif
		if (-e result.txt) then
			rm -f result.txt
		endif
		if (-e time.txt) then
			rm -f time.txt
		endif
		set seed = 0
		foreach line ("`cat Sample.txt`")
			#set start = `date +%s%3N`
			$join_dir/test.py $line $num_nodes $seed
			#set end = `date +%s%3N`
			#@ duration = $end - $start
			#echo $duration >> time.txt
			@ seed++
		end
		mv -f result.txt $case_dir/num_nodes_time/result_{$cases}_{$num_nodes}.txt
		mv -f time.txt $case_dir/num_nodes_time/time_{$cases}_{$num_nodes}.txt
	end
end
#EOF