#!/usr/bin/csh
set case_dir = "../cases/num_edges"
set join_dir = "../cases"
cp -f $case_dir/Sample.txt .
foreach prob (0.03 0.04 0.05 0.06 0.07 0.08)
	@ prob_mod = $prob*100
	foreach cases (ilp rra heu)
	#foreach cases ( rra )
		cp -f $case_dir/num_edges_${cases}.py $join_dir/test.py
		if (-e $join_dir/result.txt) then
			rm -f $join_dir/result.txt
		endif
		if (-e result.txt) then
			rm -f result.txt
		endif
		set seed = 0
		foreach line ("`cat Sample.txt`")
			$join_dir/test.py $line $prob $seed
			@ seed++
		end
		mv -f result.txt $case_dir/result_${cases}_{$prob_mod}.txt
	end
end
